const API_BASE_URL=(window.PETCLUB_API_URL||"https://api.petintelligence.com.br").replace(/\/$/,"");
const SESSION_KEY="petclub_customer_session";
const SERVICES=["Banho","Banho + Tosa","Consulta","Creche","Hotel"];
const COATS=[["","Selecione (opcional)"],["short","Pelo curto"],["medium","Pelo médio ou semilongo"],["long_straight","Pelo longo liso ou sedoso"],["long_wavy","Pelo longo ondulado"],["curly","Pelo cacheado ou encaracolado"],["double","Dupla pelagem"],["wire","Pelo duro ou pelo de arame"],["corded","Pelagem encordoada ou peculiar"],["hairless","Sem pelo"],["other","Outro"],["unknown","Não sei informar"]];
const LIFE=[["","Selecione (opcional)"],["puppy","Filhote"],["adult","Adulto"],["senior","Idoso"],["unknown","Não sei informar"]];
const NEUTERED=[["","Selecione (opcional)"],["yes","Sim"],["no","Não"],["unknown","Não sei informar"]];
let session=localStorage.getItem(SESSION_KEY)||"",customer=null,pets=[];
const $=s=>document.querySelector(s), notice=$("#notice"),success=$("#success"),bookingForm=$("#booking-form");
function petFields(prefix=""){return `<div class="field-grid two"><label>Nome do pet<input name="${prefix}name" required></label><label>Tipo do pet<select name="${prefix}animal_type" required><option>Cachorro</option><option>Gato</option><option>Outro</option></select></label><label>Porte opcional<select name="${prefix}size"><option value="">Selecione (opcional)</option><option>Pequeno</option><option>Médio</option><option>Grande</option><option>Gigante</option></select></label><label>Raça opcional<input name="${prefix}breed"></label><label>Tipo de pelagem<select name="${prefix}coat_type">${options(COATS)}</select></label><label>Fase de vida<select name="${prefix}life_stage">${options(LIFE)}</select></label><label>Castrado(a)?<select name="${prefix}neutered_status">${options(NEUTERED)}</select></label><label>Temperamento opcional<input name="${prefix}temperament"></label><label class="span-2">Observações opcionais<textarea name="${prefix}observations"></textarea></label></div>`;}
function options(items){return items.map(([v,l])=>`<option value="${v}">${l}</option>`).join("");}
$("#registration-pet").innerHTML=petFields("pet_");$("#pet-fields").innerHTML=petFields();
document.querySelectorAll("[data-auth]").forEach(b=>b.onclick=()=>showAuth(b.dataset.auth));$("#auth-back").onclick=showWelcome;
$("#login-form").onsubmit=async e=>{e.preventDefault();await authenticate("/api/customers/login",formValues(e.target));};
$("#register-form").onsubmit=async e=>{e.preventDefault();const d=formValues(e.target);const pet={};for(const k of ["name","animal_type","size","breed","coat_type","life_stage","neutered_status","temperament","observations"])pet[k]=d[`pet_${k}`]||"";await authenticate("/api/customers/register",{tutor_name:d.tutor_name,whatsapp:d.whatsapp,email:d.email,pin:d.pin,pets:[pet]});};
async function authenticate(path,body){try{const data=await api(path,{method:"POST",body:JSON.stringify(body)},false);session=data.session_token;localStorage.setItem(SESSION_KEY,session);customer=data.customer;pets=data.pets;showApp();}catch(e){warn(e.message);}}
function showAuth(type){$("#welcome").classList.add("hidden");$("#auth").classList.remove("hidden");$("#login-form").classList.toggle("hidden",type!=="login");$("#register-form").classList.toggle("hidden",type!=="register");}
function showWelcome(){$("#auth").classList.add("hidden");$("#welcome").classList.remove("hidden");}
function showApp(){$("#welcome").classList.add("hidden");$("#auth").classList.add("hidden");$("#customer-app").classList.remove("hidden");$("#customer-name").textContent=customer.tutor_name;renderPets();renderBookingPets();setDates();}
$("#logout").onclick=()=>{localStorage.removeItem(SESSION_KEY);session="";location.reload();};
$("#new-pet").onclick=()=>openPet();$("#cancel-pet").onclick=()=>$("#pet-form").classList.add("hidden");
function renderPets(){$("#pets-list").innerHTML=pets.map(p=>`<article class="pet-profile ${p.active?"":"inactive"}"><div><strong>${esc(p.name)}</strong><span>${esc(p.animal_type)}${p.size?` · ${esc(p.size)}`:""}</span><small>Pelagem: ${esc(label(COATS,p.coat_type)||"Não informada")} · Fase: ${esc(label(LIFE,p.life_stage)||"Não informada")} · Castrado(a): ${esc(label(NEUTERED,p.neutered_status)||"Não informado")}</small></div><div><button class="button secondary" data-edit="${p.pet_id}">Editar</button>${p.active?`<button class="button secondary" data-deactivate="${p.pet_id}">Desativar</button>`:"<small>Pet inativo</small>"}</div></article>`).join("");}
$("#pets-list").onclick=async e=>{const edit=e.target.closest("[data-edit]"),off=e.target.closest("[data-deactivate]");if(edit)openPet(pets.find(p=>p.pet_id===edit.dataset.edit));if(off&&confirm("Desativar este pet? O histórico será preservado.")){try{await api(`/api/customer/pets/${off.dataset.deactivate}`,{method:"PATCH",body:JSON.stringify({active:false})});await refresh();}catch(err){warn(err.message);}}};
function openPet(p=null){const f=$("#pet-form");f.reset();f.pet_id.value=p?.pet_id||"";$("#pet-form-title").textContent=p?"Editar pet":"Cadastrar novo pet";if(p)for(const k of ["name","animal_type","size","breed","coat_type","life_stage","neutered_status","temperament","observations"])f.elements[k].value=p[k]||"";f.classList.remove("hidden");f.scrollIntoView({behavior:"smooth"});}
$("#pet-form").onsubmit=async e=>{e.preventDefault();const d=formValues(e.target),id=d.pet_id;delete d.pet_id;try{await api(id?`/api/customer/pets/${id}`:"/api/customer/pets",{method:id?"PATCH":"POST",body:JSON.stringify(d)});e.target.classList.add("hidden");await refresh();}catch(err){warn(err.message);}};
async function refresh(){const data=await api("/api/customer/me");customer=data.customer;pets=data.pets;renderPets();renderBookingPets();}
function renderBookingPets(){const active=pets.filter(p=>p.active);$("#booking-pets").innerHTML=active.map(p=>`<label class="booking-pet"><input type="checkbox" data-pet-check="${p.pet_id}"><span><strong>${esc(p.name)}</strong><small>${esc(p.animal_type)}${p.size?` · ${esc(p.size)}`:""}</small><small class="stay-detail">Castrado(a): ${esc(label(NEUTERED,p.neutered_status)||"Não informado")}</small></span><select data-pet-service="${p.pet_id}" disabled>${SERVICES.map(s=>`<option>${s}</option>`).join("")}</select></label>`).join("")||"<p>Cadastre um pet ativo para agendar.</p>";document.querySelectorAll("[data-pet-check],[data-pet-service]").forEach(el=>el.onchange=updateMode);updateMode();}
function selectedPets(){return [...document.querySelectorAll("[data-pet-check]:checked")].map(c=>{const p=pets.find(x=>x.pet_id===c.dataset.petCheck),service=document.querySelector(`[data-pet-service="${c.dataset.petCheck}"]`).value;return {...p,service_type:service};});}
function group(s){return s==="Creche"?"creche":s==="Hotel"?"hotel":"timed";}
function duration(p){if(p.service_type==="Consulta")return 30;const bath={Pequeno:30,Médio:45,Grande:45,Gigante:60},groom={Pequeno:45,Médio:60,Grande:60,Gigante:90};return (p.service_type==="Banho"?bath:groom)[p.size]||0;}
function updateMode(e){if(e?.target.matches("[data-pet-check]"))document.querySelector(`[data-pet-service="${e.target.dataset.petCheck}"]`).disabled=!e.target.checked;const chosen=selectedPets(),groups=new Set(chosen.map(p=>group(p.service_type))),timed=groups.size===0||groups.has("timed");for(const id of ["#timed-date-label","#timed-hour-label"])$(id).classList.toggle("hidden",!timed);for(const id of ["#entry-label","#exit-label"])$(id).classList.toggle("hidden",timed);const mixed=groups.size>1,total=chosen.reduce((n,p)=>n+duration(p),0);$("#duration-note").textContent=mixed?"Não é permitido misturar serviços com horário, Creche e Hotel.":timed&&chosen.length?`Duração total: ${total} minutos.`:chosen.length?`Capacidade calculada para ${chosen.length} pet(s) no intervalo inclusivo.`:"Selecione pelo menos um pet.";document.querySelectorAll(".stay-detail").forEach(x=>x.classList.toggle("hidden",timed));if(timed&&chosen.length&&!mixed)loadAvailability(total);}
function setDates(){const today=new Date().toISOString().slice(0,10);for(const n of ["appointment_date","entry_date","exit_date"]){bookingForm.elements[n].min=today;bookingForm.elements[n].value=today;}bookingForm.elements.appointment_date.onchange=()=>loadAvailability(selectedPets().reduce((n,p)=>n+duration(p),0));}
async function loadAvailability(duration){try{const d=bookingForm.elements.appointment_date.value,data=await api(`/api/availability?date=${d}&duration_minutes=${duration}`,{},false);bookingForm.elements.appointment_hour.innerHTML='<option value="">Selecione</option>'+data.slots.map(s=>`<option ${s.available?"":"disabled"}>${s.time}${s.available?"":" - indisponível"}</option>`).join("");}catch(e){warn(e.message);}}
bookingForm.elements.transport_option.onchange=()=>{const needed=bookingForm.elements.transport_option.value!=="Não, vou levar até a loja";$("#transport-fields").classList.toggle("hidden",!needed);bookingForm.elements.address.required=needed;};
bookingForm.onsubmit=async e=>{e.preventDefault();const chosen=selectedPets(),groups=new Set(chosen.map(p=>group(p.service_type)));if(!chosen.length)return warn("Selecione pelo menos um pet.");if(groups.size!==1)return warn("Não é permitido misturar serviços com horário, Creche e Hotel.");if([...groups][0]==="timed"&&chosen.some(p=>p.service_type!=="Consulta"&&!p.size))return warn("Informe o porte no perfil para Banho ou Banho + Tosa.");const d=formValues(e.target),timed=[...groups][0]==="timed",transport=d.transport_option!=="Não, vou levar até a loja";if(transport&&!d.address)return warn("Informe o endereço completo para o leva e traz.");const payload={pets:chosen.map(p=>({pet_id:p.pet_id,service_type:p.service_type})),appointment_date:timed?d.appointment_date:"",appointment_hour:timed?d.appointment_hour:"",entry_date:timed?"":d.entry_date,exit_date:timed?"":d.exit_date,transport_needed:transport,transport_label:d.transport_option,address:transport?d.address:"",address_complement:transport?d.address_complement:"",neighborhood:transport?d.neighborhood:"",reference_point:transport?d.reference_point:"",location_link:transport?d.location_link:"",notes:d.notes||""};try{await api("/api/bookings",{method:"POST",body:JSON.stringify(payload)});success.textContent="Agendamento recebido! Em breve a equipe do PetClub SP irá confirmar.";success.classList.remove("hidden");e.target.reset();setDates();renderBookingPets();}catch(err){warn(err.message);}};
async function api(path,opt={},auth=true){const headers={"Content-Type":"application/json",...(opt.headers||{})};if(auth&&session)headers.Authorization=`Bearer ${session}`;const r=await fetch(API_BASE_URL+path,{...opt,headers});const body=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(body.error||`Erro HTTP ${r.status}`);e.status=r.status;throw e;}return body;}
function warn(t){notice.textContent=t;notice.classList.remove("hidden");notice.scrollIntoView({behavior:"smooth"});}function label(list,v){return list.find(x=>x[0]===v)?.[1]||v;}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);}
(async()=>{if(!session)return;try{const d=await api("/api/customer/me");customer=d.customer;pets=d.pets;showApp();}catch{localStorage.removeItem(SESSION_KEY);session="";}})();
