const API_BASE_URL=(window.PETCLUB_API_URL||"https://api.petintelligence.com.br").replace(/\/$/,"");
const SERVICES=["Banho","Banho + Tosa","Consulta","Creche","Hotel"];
const COATS=[["","Selecione (opcional)"],["short","Pelo curto"],["long_straight","Pelo longo"]];
const LIFE=[["","Selecione (opcional)"],["puppy","Filhote"],["adult","Adulto"],["senior","Idoso"],["unknown","Não sei informar"]];
const NEUTERED=[["","Selecione (opcional)"],["yes","Sim"],["no","Não"],["unknown","Não sei informar"]];
const form=document.querySelector("#booking-form"),notice=document.querySelector("#notice"),success=document.querySelector("#success");
const panels=[...document.querySelectorAll(".form-step")],tabs=[...document.querySelectorAll(".step-tab")];
let currentStep=0,petSequence=0;
const $=selector=>document.querySelector(selector);
init();
function init(){addPet();$("#add-pet").onclick=addPet;$("#pets-editor").onclick=removePet;$("#pets-editor").oninput=renderServices;$("#pet-services").onchange=updateMode;$("#transport-option").onchange=updateTransport;$("#appointment-date").onchange=loadAvailability;$("#back-button").onclick=()=>showStep(currentStep-1);$("#next-button").onclick=nextStep;tabs.forEach(tab=>tab.onclick=()=>{const step=Number(tab.dataset.step);if(step<currentStep)showStep(step);});form.onsubmit=submitBooking;setDates();updateTransport();showStep(0);}
function options(items){return items.map(([value,label])=>`<option value="${value}">${label}</option>`).join("");}
function petCard(id){return `<fieldset class="booking-pet-editor" data-pet="${id}"><legend>Pet <span class="pet-number"></span></legend><div class="field-grid two"><label>Nome do pet<input data-field="pet_name" required></label><label>Tipo do pet<select data-field="pet_type" required><option>Cachorro</option><option>Gato</option><option>Outro</option></select></label><label>Porte<select data-field="pet_size" required><option value="">Selecione</option><option>Pequeno</option><option>Médio</option><option>Grande</option><option>Gigante</option></select></label><label>Tipo de pelagem<select data-field="coat_type">${options(COATS)}</select></label><label>Fase de vida<select data-field="life_stage">${options(LIFE)}</select></label><label>Castrado(a)?<select data-field="neutered_status">${options(NEUTERED)}</select></label></div><button type="button" class="button secondary remove-pet">Remover pet</button></fieldset>`;}
function addPet(){petSequence+=1;$("#pets-editor").insertAdjacentHTML("beforeend",petCard(petSequence));renumberPets();renderServices();}
function removePet(event){const button=event.target.closest(".remove-pet");if(!button)return;if(document.querySelectorAll("[data-pet]").length===1)return warn("Inclua pelo menos um pet neste agendamento.");button.closest("[data-pet]").remove();renumberPets();renderServices();}
function renumberPets(){document.querySelectorAll("[data-pet]").forEach((card,index)=>{card.querySelector(".pet-number").textContent=index+1;card.querySelector(".remove-pet").classList.toggle("hidden",document.querySelectorAll("[data-pet]").length===1);});}
function pets(){return [...document.querySelectorAll("[data-pet]")].map(card=>{const pet={client_id:card.dataset.pet};card.querySelectorAll("[data-field]").forEach(field=>pet[field.dataset.field]=field.value.trim());const service=$( `[data-service-pet="${card.dataset.pet}"]`);pet.service_type=service?.value||"Banho";return pet;});}
function renderServices(){const previous=new Map([...document.querySelectorAll("[data-service-pet]")].map(select=>[select.dataset.servicePet,select.value]));$("#pet-services").innerHTML=pets().map((pet,index)=>`<article class="pet-service-row"><div><strong>${escapeHtml(pet.pet_name||`Pet ${index+1}`)}</strong><small>${escapeHtml(pet.pet_type||"Pet")}${pet.pet_size?` · ${escapeHtml(pet.pet_size)}`:""}</small></div><label>Serviço<select data-service-pet="${pet.client_id}">${SERVICES.map(service=>`<option ${service===(previous.get(pet.client_id)||pet.service_type)?"selected":""}>${service}</option>`).join("")}</select></label></article>`).join("");updateMode();}
function group(service){return service==="Creche"?"creche":service==="Hotel"?"hotel":"timed";}
function duration(pet){if(pet.service_type==="Consulta")return 30;const bath={Pequeno:30,Médio:45,Grande:45,Gigante:60},groom={Pequeno:45,Médio:60,Grande:60,Gigante:90};return (pet.service_type==="Banho"?bath:groom)[pet.pet_size]||0;}
function bookingMode(list=pets()){const groups=new Set(list.map(pet=>group(pet.service_type)));return {group:groups.size===1?[...groups][0]:"",mixed:groups.size>1,total:list.reduce((sum,pet)=>sum+duration(pet),0)};}
function updateMode(){const mode=bookingMode();$("#duration-note").textContent=mode.mixed?"Não é permitido misturar serviços com horário, Creche e Hotel.":mode.group==="timed"?`Duração total: ${mode.total} minutos.`:mode.group?`Capacidade para ${pets().length} pet(s) no período selecionado.`:"";$("#timed-date-fields").classList.toggle("hidden",mode.group!=="timed");$("#range-date-fields").classList.toggle("hidden",mode.group==="timed");if(mode.group==="timed")loadAvailability();}
function setDates(){const today=new Date().toISOString().slice(0,10);for(const field of [$("#appointment-date"),$("#entry-date"),$("#exit-date")]){field.min=today;field.value=today;}}
async function loadAvailability(){const mode=bookingMode();if(mode.group!=="timed")return;const date=$("#appointment-date").value,hour=$("#appointment-hour");hour.innerHTML='<option value="">Carregando horários...</option>';try{const data=await api(`/api/availability?date=${encodeURIComponent(date)}&duration_minutes=${mode.total}`);hour.innerHTML='<option value="">Selecione um horário</option>'+data.slots.map(slot=>`<option value="${slot.time}" ${slot.available?"":"disabled"}>${slot.time}${slot.available?"":" - indisponível"}</option>`).join("");$("#date-message").textContent="O último horário de início é 16:30.";}catch(error){hour.innerHTML='<option value="">Não foi possível carregar</option>';warn(error.message);}}
function updateTransport(){const needed=$("#transport-option").value!=="Não, vou levar até a loja";$("#transport-fields").classList.toggle("hidden",!needed);form.elements.address.required=needed;if(!needed)for(const field of $("#transport-fields").querySelectorAll("input"))field.value="";}
function values(){const data={};for(const field of form.elements)if(field.name&&!field.disabled&&(!["checkbox","radio"].includes(field.type)||field.checked))data[field.name]=field.value;return data;}
function validateStep(){notice.classList.add("hidden");const fields=[...panels[currentStep].querySelectorAll("input,select,textarea")];if(!fields.every(field=>field.reportValidity()))return false;if(currentStep===1&&!pets().length)return warn("Inclua pelo menos um pet."),false;if(currentStep===2&&bookingMode().mixed)return warn("Não é permitido misturar serviços com horário, Creche e Hotel."),false;if(currentStep===4){const mode=bookingMode();if(mode.group==="timed"&&(!form.elements.appointment_date.value||!form.elements.appointment_hour.value))return warn("Selecione a data e o horário."),false;if(mode.group!=="timed"&&(!form.elements.entry_date.value||!form.elements.exit_date.value))return warn("Informe as datas de entrada e saída."),false;if(mode.group!=="timed"&&form.elements.exit_date.value<form.elements.entry_date.value)return warn("A data de saída não pode ser anterior à entrada."),false;}return true;}
function nextStep(){if(validateStep())showStep(currentStep+1);}
function showStep(step){currentStep=Math.max(0,Math.min(5,step));panels.forEach(panel=>panel.classList.toggle("active",Number(panel.dataset.stepPanel)===currentStep));tabs.forEach(tab=>tab.classList.toggle("active",Number(tab.dataset.step)===currentStep));$("#back-button").disabled=currentStep===0;$("#next-button").classList.toggle("hidden",currentStep===5);$("#confirm-button").classList.toggle("hidden",currentStep!==5);if(currentStep===2)renderServices();if(currentStep===5)renderSummary();document.querySelector(".step-layout").scrollIntoView({behavior:"smooth",block:"start"});}
function payload(){const data=values(),list=pets(),mode=bookingMode(list),transport=data.transport_option!=="Não, vou levar até a loja",first=list[0];return {tutor_name:data.tutor_name,whatsapp:data.whatsapp,email:data.email||"",pet_name:first.pet_name,pet_type:first.pet_type,pet_size:first.pet_size,coat_type:first.coat_type||"Não informado",temperament:"Não informado",service_type:first.service_type,pets:list.map(({client_id,...pet})=>pet),pet_count:list.length,service_group:mode.group,calculated_duration_minutes:mode.group==="timed"?mode.total:null,transport_needed:transport,transport_label:data.transport_option,address:transport?data.address||"":"",address_complement:transport?data.address_complement||"":"",neighborhood:transport?data.neighborhood||"":"",reference_point:transport?data.reference_point||"":"",location_link:transport?data.location_link||"":"",appointment_date:mode.group==="timed"?data.appointment_date:"",appointment_hour:mode.group==="timed"?data.appointment_hour:"",entry_date:mode.group==="timed"?"":data.entry_date,exit_date:mode.group==="timed"?"":data.exit_date,notes:data.notes||"",status:"Novo"};}
function renderSummary(){const data=payload(),timed=data.service_group==="timed",items=[["Tutor",`${data.tutor_name} · ${data.whatsapp}${data.email?` · ${data.email}`:""}`],["Pets e serviços",data.pets.map(pet=>`${pet.pet_name} — ${pet.service_type}`).join("; ")],[timed?"Data e horário":"Entrada e saída",timed?`${formatDate(data.appointment_date)} às ${data.appointment_hour}`:`${formatDate(data.entry_date)} a ${formatDate(data.exit_date)}`],["Leva e traz",data.transport_label],["Endereço",data.transport_needed?data.address:"Não se aplica"]];if(timed)items.splice(3,0,["Duração total",`${data.calculated_duration_minutes} minutos`]);$("#booking-summary").innerHTML=items.map(([label,value])=>`<div class="summary-item"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`).join("");}
async function submitBooking(event){event.preventDefault();if(!validateStep())return;const button=$("#confirm-button");button.disabled=true;button.textContent="Enviando...";try{await api("/api/bookings",{method:"POST",body:JSON.stringify(payload())});notice.classList.add("hidden");success.classList.remove("hidden");form.reset();$("#pets-editor").innerHTML="";addPet();setDates();updateTransport();showStep(0);success.scrollIntoView({behavior:"smooth"});}catch(error){warn(error.message);}finally{button.disabled=false;button.textContent="Confirmar agendamento";}}
async function api(path,options={}){const response=await fetch(API_BASE_URL+path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}}),body=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(body.error||`Erro HTTP ${response.status}`);error.status=response.status;throw error;}return body;}
function warn(message){notice.textContent=message;notice.classList.remove("hidden");notice.scrollIntoView({behavior:"smooth",block:"center"});}
function formatDate(value){if(!value)return"Não informado";const [year,month,day]=value.split("-");return `${day}/${month}/${year}`;}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[char]);}
